### PR TITLE
Address Issue #8 - Add support for receiving a boolean that is initially false

### PR DESCRIPTION
**Pull request by slawomir-brzezinski-at-interxion**
This fixes the problem outlined in issue #8.

It achieves this by introducing two new 'Per-Property settings': `ancestorMatches` and `ancestorObservedItem`. 

Have a look at [their doc in Readme](https://github.com/zlamma/properties-from-ancestor-behavior/blob/b8698c07f8f8d7ec049a3993771967eaa7b03bb3/README.md#api-reference---per-property-settings) for more details about the idea.

There's also some 'cosmetic fix' commits. Each commit has a small summary in message. The most important commit is the last one (the one that implements the behavior change).

### CODE REVIEW

**Review by ma499 — COMMENTED** [review]
Use of let keyword implies browser supports ES2015. Or that server is expected to transpile (as per Polymer 2.0 guidance). I don't have a problem with it, but I think this is a major change - as, I think, it reduces the current level of browser compatibility. Probably best to release with Polymer 2.0 changes.

**Comment by slawomir-brzezinski-at-interxion** [comment]
@ma499 while `let` is indeed ES2015, I migrated early because this feature happens to be already in [IE11](https://caniuse.com/#feat=let). Even Polymer [only supports IE11](https://www.polymer-project.org/1.0/docs/browsers).  
Or do you have other browsers in mind?

**Comment by ma499** [comment]
That’s less than the impact I had thought. However, I believe: a) IE11 only supports ‘let’ when the script opts in to script mode, b) Polymer supports Safari 7+ but (iOS ,in particular) didn’t get ‘let’ until v10: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let

**Comment by slawomir-brzezinski-at-interxion** [comment]
Good spot on the need for `'use strict';` - I totally missed that.

Yeah, I must admit that I kinda guessed that Safari should be fine judging by the [0.56% market share of iOS Safari 9.2](https://caniuse.com/#feat=let), but since I never owned anything Apple, I don't really know if we aren't cutting anyone important off.

Are we? Have I left out any important Apple devices? Cuz if not, I'll just add a quick `'use strict;'` and we'll be sorted.

**Comment by ma499** [comment]
I don't care for unsupported versions of Safari :-)

**Review by ma499 — APPROVED** [review]

**Review by rickyattiliaaq — APPROVED** [review]

**Pull request merged**
