### PR TITLE
Address Issue #6 - Add support for different attribute/property name in ancestor

### PR DESCRIPTION
**Pull request by zlamma**
This fixes the problem outlined in issue #6.

It achieves this by introducing a new 'Per-Property setting': `nameOnAncestor`. 

Have a look at [its doc in Readme](https://github.com/zlamma/properties-from-ancestor-behavior/blob/Issue6SupportDifferentNameInAncestor/README.md#api-reference---per-property-settings) for more details about the idea.

### CODE REVIEW

**Review by ma499 — APPROVED** [review]
I would have gone with something like 'ancestorName' rather than 'nameOnAncestor' but it's fine :-)

**Comment by slawomir-brzezinski-at-interxion** [comment]
Yes, `ancestorName` came to my mind only to make me realize that ancestor is an element, and it has a name, so I definitely wanted to stay away from that interpretation.

We're asking here about the name of the property on the ancestor so I settled for `nameOnAncestor` (since we're already in the context of defining a property, I allowed myself to omit the 'property').

But it's true that it's losing the nice convention of [all other options related to ancestor *starting* with ancestor](https://github.com/zlamma/properties-from-ancestor-behavior/blob/Issue6SupportDifferentNameInAncestor/README.md#api-reference---per-property-settings), so maybe address both convention and ambiguity concerns by letting go on the terseness and go with:
`ancestorPropertyName`

What do you think @ma499 ?

**Comment by ma499** [comment]
Yes, I think ancestorPropertyName (or maybe ancestorPropertyAlias - or possibly an array of ancestorPropertySynonyms!) would be fine.

**Comment by ma499** [comment]
I think ancestoryProperty[Name|Alias|Synonym] fine. I might be tempted to make it an array in which case I'd be more inclined to pick a name on the right rather than on the left :-)

**Comment by slawomir-brzezinski-at-interxion** [comment]
I like `ancestorPropertyAlias` - intuitive and short.  

An array would rather be an extra feature, which I'd rather wait until I see a need for.
That's because it has its own impact on the complexity (code and new test cases) and might also complicate implementing a different case I was thinking of covering - detecting when an attribute appears at any level (like the corner case of having fieldset inside a fieldset, where disabled is introduced only to the outer one).

**Review by rickyattiliaaq — APPROVED** [review]

**Pull request merged**
